language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mkipfer/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mkipfer/docker-react npm run test

